[package]
name = "backend"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { version = "0.8.4", features = ["tracing", "http2"] }
rust-embed = "8.7.2"
tokio = { version = "1.45.1", features = ["full"] }
mime_guess = "2.0.5"
snafu = "0.8.6"
diesel = { version = "2.2.12", features = ["sqlite", "returning_clauses_for_sqlite_3_35"] }
libsqlite3-sys = { version = "0.35.0", features = ["bundled"] }
diesel_migrations = { version = "2.2.0", features = ["sqlite"] }
serde_json = "1.0.142"
serde_derive = "1.0.219"
serde = "1.0.219"
dotenvy = "0.15.7"
chrono = "0.4.41"
uuid = { version = "1.18.0", features = ["v4", "v7"] }
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
tracing = "0.1.41"
tower-http = { version = "0.6.6", features = ["trace", "cors"] }
